### ISSUE TITLE
peanut gallery feedback

### ISSUE THREAD

**Issue by jgravois** [Esri/geotour-js#2]
- i like the code, comprehensive doc and homespun/non sterile language.
- i know i'm feeble minded, but I found the fact that the code snippets and live samples skip specifying a custom service url more confusing than helpful.
- no need to link to the JSAPI in a section called Requirements and then again in another called [Resources](https://github.com/Esri/geotour-js#resources) directly below
- as configurable as everything else is, it'd make the tour substantially more flexible if developers could just pass field names for sequencing and labeling.  at the very least we'd get to see some nonsensical tours by objectid.

![good jorb](https://cdn.drawception.com/images/panels/2015/3-2/fW4pZStr6b-1.png)

**Comment by nixta** [comment]
Why come I dun not see'd this until now? Thanks for the feedback! Makes good sense.

I avoided URLs because at the time, ArcGIS Online was broken and couldn't create URLs from directions, yet, without manual hacking. I will revisit.

I thought you could just pass fields into the URL to specify field names. Not sure I follow. Let's discuss.

**Comment by jgravois** [comment]
you are my friend.
